name = "line-crm-worker"
main = "src/index.ts"
compatibility_date = "2024-12-01"
workers_dev = true
account_id = "8b7e570059516de5d6009187ef6a12a0"

# API_KEY is set via `wrangler secret put API_KEY`
# Do NOT hardcode secrets here

[vars]
WORKER_URL = "https://line-crm-worker.kairu0119-gmail-com.workers.dev"

[[d1_databases]]
binding = "DB"
database_name = "line-crm"
database_id = "9fe1eb5e-08e5-47f8-a7f7-a77388da0028"

[triggers]
crons = ["*/5 * * * *"]
